const majors = [
  "Agroecology B.A.",
  "Ancient Studies B.A.",
  "Anthropology B.A.",
  "Applied Linguistics and Multilingualism B.A.",
  "Applied Mathematics B.S.",
  "Applied Physics B.S.",
  "Art & Design: Games + Playable Media B.A.",
  "Art B.A.",
  "Biochemistry and Molecular Biology B.S.",
  "Biology B.A.",
  "Biology B.S.",
  "Biomolecular Engineering and Bioinformatics B.S.",
  "Biotechnology B.A.",
  "Business Management Economics B.A.",
  "Chemistry B.A.",
  "Chemistry B.S.",
  "Cognitive Science B.S.",
  "Community Studies B.A.",
  "Computer Engineering B.S.",
  "Computer Science B.A.",
  "Computer Science B.S.",
  "Computer Science: Computer Game Design B.S.",
  "Creative Technologies B.A.",
  "Critical Race and Ethnic Studies B.A.",
  "Earth Sciences B.S.",
  "Earth Sciences/Anthropology Combined Major B.A.",
  "Ecology and Evolution B.S.",
  "Economics B.A.",
  "Economics/Mathematics Combined B.A.",
  "Education, Democracy, and Justice B.A.",
  "Electrical Engineering B.S.",
  "Environmental Sciences B.S.",
  "Environmental Studies B.A.",
  "Environmental Studies/Biology Combined Major B.A.",
  "Environmental Studies/Earth Sciences Combined Major B.A.",
  "Environmental Studies/Economics Combined Major B.A.",
  "Feminist Studies B.A.",
  "Film and Digital Media B.A.",
  "Global and Community Health B.A.",
  "Global and Community Health B.S.",
  "Global Economics B.A.",
  "History B.A.",
  "History of Art and Visual Culture B.A.",
  "Jewish Studies B.A.",
  "Language Studies B.A.",
  "Latin American and Latino Studies B.A.",
  "Latin American and Latino Studies/Education, Democracy, and Justice B.A.",
  "Latin American and Latino Studies/Politics Combined B.A.",
  "Latin American and Latino Studies/Sociology Combined B.A.",
  "Legal Studies B.A.",
  "Linguistics B.A.",
  "Literature B.A.",
  "Marine Biology B.S.",
  "Mathematics B.A.",
  "Mathematics B.S.",
  "Mathematics Education B.A.",
  "Mathematics Theory and Computation B.S.",
  "Microbiology B.S.",
  "Molecular, Cell, and Developmental Biology B.S.",
  "Music B.A.",
  "Music B.M.",
  "Network and Digital Technology B.A.",
  "Neuroscience B.S.",
  "Philosophy B.A.",
  "Physics (Astrophysics) B.S.",
  "Physics B.S.",
  "Plant Sciences B.S.",
  "Politics B.A.",
  "Psychology B.A.",
  "Robotics Engineering B.S.",
  "Science Education B.S.",
  "Sociology B.A.",
  "Spanish Studies B.A.",
  "Technology and Information Management B.S.",
  "Theater Arts B.A."
]

export default majors